#!/usr/bin/env zsh

################ Dotbot symlinks - Do Not Update ################

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

################ Feel Free To Update Anything Below ################

echo "export XDG_CONFIG_HOME=\"$HOME/.config\"" >> ~/.zshrc
echo "export ZDOTDIR=\"$XDG_CONFIG_HOME/zsh\"" >> ~/.zshrc
echo "source ${XDG_CONFIG_HOME}/zsh/aliases" >> ~/.zshrc
echo "source ${XDG_CONFIG_HOME}/zsh/exports" >> ~/.zshrc
source ~/.zshrc

# Check to see if Homebrew is installed, and install it if it is not
command -v brew >/dev/null 2>&1 || { echo >&2 "Installing Homebrew"; \
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; }

brew bundle --file=- <<-EOS
brew "neovim"
brew "fzf"
brew "ripgrep"
brew "trash"
brew "standard"
brew "jesseduffield/lazygit/lazygit"
brew "awscli"
brew "node"
brew "tree"
brew "nvm"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/terraform-ls"
cask "homebrew/cask-fonts/font-hack-nerd-font"
cask "session-manager-plugin"
EOS

if [ ! -d "${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/.zprezto" ] ; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/.zprezto"
  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
fi

/opt/homebrew/opt/fzf/install --all --xdg

# Use the highest possible version of node per-project
nvm alias default node

aws configure set region us-east-1
