require "user.options"
require "user.hop"
require "user.keymaps"
require "user.plugins"
require "user.lualine"
require "user.telescope"
-- require "user.whichkey"
require "user.treesitter"
require "user.cutlass"
require "user.lsp"
require "user.cmp"
require "user.toggleterm"
